version: '3'
services:
  spark-master:
    image: bitnami/spark:3.5.1
    hostname: spark-master
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"  # Spark Master UI
      - "7077:7077"  # Spark Master port for worker registration and job submission
    networks:
      - spark-network

  spark-worker:
    image: bitnami/spark:3.5.1
    hostname: spark-worker
    # container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    networks:
      - spark-network
    ports:
      - "8081"  # Spark Worker UI (Docker assigns a random port on the host)
      - "4040"  # Dynamically map Application UI ports (4040-4050)
    depends_on:
      - spark-master
    # ports:
    #   - "8081:8081"  # Spark Worker UI

  # Optional: Spark History Server
  spark-history:
    image: bitnami/spark:3.5.1
    hostname: spark-history
    container_name: spark-history
    environment:
      - SPARK_MODE=history-server
    ports:
      - "18080:18080"  # Spark History Server UI
    volumes:
      - ./history:/tmp/spark-events  # Mount to persist history logs
    networks:
      - spark-network
    depends_on:
      - spark-master

  # Flask API service
  flask-api:
    build: ./flask-app  # We'll create this directory with a Dockerfile for Flask
    container_name: flask-api
    ports:
      - "5000:5000"  # Flask API will be accessible on port 5000
    networks:
      - spark-network  # Same network to allow communication with Spark cluster
    depends_on:
      - spark-master
      - spark-worker

networks:
  spark-network:
    driver: bridge
